import AppKit

final class PasteboardWatcher {
    let store = ClipboardStore()

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?

    /// The org.nspasteboard.* convention (see nspasteboard.org): password
    /// managers and other apps tag a copy with one of these to mean "don't
    /// remember this." Not built into AppKit - these are raw UTI strings by
    /// convention only. Skipping a poll entirely when any is present keeps
    /// secrets out of history.
    private let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    init() {
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.pollNow()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Checks the pasteboard once and captures a new entry if it changed
    /// since the last check. Called on a timer in production; called
    /// directly in tests to avoid depending on timer/run-loop timing.
    ///
    /// Types are checked in order of specificity, since a single copy often
    /// exposes more than one representation (e.g. a Finder file copy also
    /// exposes a plain-string path) - the most specific match wins so a file
    /// copy is stored as `.fileURLs`, not `.text`.
    func pollNow() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        guard ignoredTypes.isDisjoint(with: pasteboard.types ?? []) else { return }

        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            store.add(.fileURLs(urls))
            return
        }

        if let color = NSColor(from: pasteboard) {
            let rgb = color.usingColorSpace(.deviceRGB) ?? color
            store.add(.color(ColorComponents(
                red: rgb.redComponent,
                green: rgb.greenComponent,
                blue: rgb.blueComponent,
                alpha: rgb.alphaComponent
            )))
            return
        }

        if let imageData = pasteboard.data(forType: .tiff) ?? pasteboard.data(forType: .png),
           let pngData = normalizeToPNG(imageData) {
            store.add(.image(pngData))
            return
        }

        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            store.add(.text(text))
        }
    }

    /// Stores images as PNG regardless of source format (TIFF is the more
    /// common one, e.g. from a Finder image copy) so the picker only ever
    /// has to render one image format.
    private func normalizeToPNG(_ imageData: Data) -> Data? {
        guard let bitmap = NSBitmapImageRep(data: imageData) else { return nil }
        return bitmap.representation(using: .png, properties: [:])
    }
}
